### ISSUE TITLE
Create a release note for 0.0.9 and tag the github project

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/java-buildpack-client#74]
## TODO

As a new release `0.0.9` has been build/push on maven central https://repo1.maven.org/maven2/dev/snowdrop/buildpack-client/0.0.9/, we should then create a release note and at least tag the project

**Comment by BarDweller** [comment]
tag was auto created by the release action and existed before this issue was raised (https://github.com/snowdrop/java-buildpack-client/releases/tag/0.0.9). This project only releases to maven central, not to github, so there is nowhere to post release notes. The Readme is current for the latest version.
